name: ipa
version: 0.1.1
homepage: https://github.com/JosephMoniz/ipa
description: >
  A Dart web framework with taste
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  option:          '>=0.3.0 <0.4.0'
  either:          '>=0.1.0 <0.2.0'
  dictionary:      '>=0.2.0 <0.3.0'
  http_router:     '>=0.2.0 <0.3.0'
  service_manager: '>=0.1.0 <0.2.0'
